"""ediçao do models de conta

Revision ID: 646bfd97212d
Revises: c92adcff678b
Create Date: 2025-11-19 09:57:36.214688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646bfd97212d'
down_revision: Union[str, Sequence[str], None] = 'c92adcff678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('conta_cliente_id_fkey'), 'conta', type_='foreignkey')
    op.create_foreign_key(None, 'conta', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conta', type_='foreignkey')
    op.create_foreign_key(op.f('conta_cliente_id_fkey'), 'conta', 'cliente', ['cliente_id'], ['id'])
    op.alter_column('conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
