"""ediçao do tablename de Conta pra conta

Revision ID: 77ff1c821517
Revises: c947ce16ff23
Create Date: 2025-11-15 12:11:27.393269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ff1c821517'
down_revision: Union[str, Sequence[str], None] = 'c947ce16ff23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Conta_id'), table_name='Conta')
    op.drop_table('Conta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_do_banco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numero_da_agencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero_da_conta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('Conta_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Conta_pkey'))
    )
    op.create_index(op.f('ix_Conta_id'), 'Conta', ['id'], unique=False)
    # ### end Alembic commands ###
