"""Criaçao da tabela Usuario no banco

Revision ID: 7ee296f13849
Revises: 9b8716ce4490
Create Date: 2025-11-10 13:24:44.938619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee296f13849'
down_revision: Union[str, Sequence[str], None] = '9b8716ce4490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.drop_index(op.f('ix_Conta_id'), table_name='Conta')
    op.drop_table('Conta')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cliente_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cliente_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('Conta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_do_banco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numero_da_agencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero_da_conta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('Conta_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Conta_pkey'))
    )
    op.create_index(op.f('ix_Conta_id'), 'Conta', ['id'], unique=False)
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
