"""adiçao das colunas clienteid,cliente,contas

Revision ID: 9b8716ce4490
Revises: 207172317793
Create Date: 2025-11-08 21:29:15.249973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8716ce4490'
down_revision: Union[str, Sequence[str], None] = '207172317793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Conta', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Conta', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Conta', type_='foreignkey')
    op.drop_column('Conta', 'cliente_id')
    # ### end Alembic commands ###
