"""ediçao do cliente_id no schemas e no models

Revision ID: b33a6be60a68
Revises: ac49b97dfc4f
Create Date: 2025-11-15 11:20:32.528005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33a6be60a68'
down_revision: Union[str, Sequence[str], None] = 'ac49b97dfc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
