"""adiçao  da coluna email no models de cliente

Revision ID: c92adcff678b
Revises: 77ff1c821517
Create Date: 2025-11-19 09:30:26.297001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92adcff678b'
down_revision: Union[str, Sequence[str], None] = '77ff1c821517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.add_column('cliente', sa.Column('email', sa.String(length=100), nullable=True))
    op.alter_column('cliente', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cliente', 'idade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cliente', 'idade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cliente', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cliente', 'email')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
