"""ediçao do models de conta

Revision ID: c947ce16ff23
Revises: b33a6be60a68
Create Date: 2025-11-15 11:27:16.518374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c947ce16ff23'
down_revision: Union[str, Sequence[str], None] = 'b33a6be60a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Conta', 'numero_da_conta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Conta', 'numero_da_agencia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Conta', 'nome_do_banco',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
